### ISSUE TITLE
How to install ?

### ISSUE THREAD

**Issue by rvion** [CRogers/stack-ide-atom#1]
Cloning into `$HOME/.atom/packages` then launching atom gives me an exception

**Atom Version**: 1.0.2
**System**: Mac OS X 10.10.4
**Thrown From**: [stack-ide-atom](https://github.com/atom/stack-ide-atom) package, v0.1.0
### Stack Trace

Failed to load the stack-ide-atom package

```
At Cannot find module './haskell/generated/haskell'

Error: Cannot find module './haskell/generated/haskell'
    at Module._resolveFilename (module.js:328:15)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at Object.<anonymous> (/Users/RemiVion/.atom/packages/stack-ide-atom/lib/stack-ide-atom.coffee:4:13)
    at Object.<anonymous> (/Users/RemiVion/.atom/packages/stack-ide-atom/lib/stack-ide-atom.coffee:8:4)
    at Module._compile (module.js:452:26)
    at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
    at Module.load (module.js:347:32)
```
### Commands

```
```
### Config

``` json
{
  "core": {}
}
```
### Installed Packages

``` coffee
# User
stack-ide-atom, v0.1.0

# Dev
No dev packages
```

**Comment by CRogers** [comment]
Cool, so I literally got to a place last night where it will show you a single error (and only one error) as a highlight when pressing `ctrl+alt+e` and nothing else. This week I'm planning to make the build work (which is going to be a prerequisite for any kind of contributions) and hopefully release an initial version onto [atom.io](http://atom.io/) that will simply highlight all your errors. I'll also write a README about how to get started.

Until then, you need to:

1) Install new node/npm
2) Install docker (and boot2docker for OS X)
3) `npm install`
4) `./docker-gulp build`

You can also install the version of `stack-ide` this works with by doing `./gulp build-stack-ide` (you'll need it installed for it to be able to run).

And that should be that. Look in the gulpfile for more things to do (like `./docker-gulp test`). If you get errors about `stack ENOENT` or similar you need `stack` on your PATH - make sure to start Atom using `atom .` from the console.

Feel free to report issues, but remember the scope of project at this very moment is just highlighting one source error until I work on it again (probably most nights this week).
